### ISSUE TITLE
We Need A Story

### ISSUE THREAD

**Issue by GraVeu** [JoshSank/Project-NightShade#1]
Basically title.

Before we start development we need a story to develop with. Talk on skype, when we finalize something add a text file to the develop branch.

**Comment by SJawesome** [comment]
I think we should... nevermind I got nothing .

**Comment by SJawesome** [comment]
[ProjectNightShade.docx](https://github.com/JoshSank/Project-NightShade/files/332254/ProjectNightShade.docx)
